name: Github pages

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Yarn lint
        run: yarn lint

      - name: Yarn build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Build site
        run: yarn build:site

      - name: Release pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: ./packages/ReactDagEditor/.static-demo
          commit_message: Update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
