name: Github pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Build site
        run: yarn build:site

      - name: Release pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: ./dist/storybook/react-dag-editor
          commit_message: Update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
